//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskNet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class workflowServiceEntities : DbContext
    {
        public workflowServiceEntities()
            : base("name=workflowServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<service_config> service_config { get; set; }
        public virtual DbSet<tarea> tareas { get; set; }
        public virtual DbSet<tareas_ejecutadas> tareas_ejecutadas { get; set; }
        public virtual DbSet<track> tracks { get; set; }
    }
}
