//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_config
    {
        public int id { get; set; }
        public int intervalo_ms { get; set; }
        public string mensaje_inicio { get; set; }
        public string mensaje_detenido { get; set; }
        public string mensaje_intervalo { get; set; }
        public string service_log { get; set; }
        public string nombre_source { get; set; }
    }
}
