//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tarea()
        {
            this.tareas_ejecutadas = new HashSet<tareas_ejecutadas>();
        }
    
        public int id { get; set; }
        public string metodo { get; set; }
        public string nombre_contrato { get; set; }
        public string url_servicio { get; set; }
        public string parametros { get; set; }
        public System.TimeSpan tiempo_ejecucion { get; set; }
        public System.DateTime ultima_ejecucion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tareas_ejecutadas> tareas_ejecutadas { get; set; }
    }
}
