//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tareas_ejecutadas
    {
        public int id { get; set; }
        public Nullable<int> id_tarea { get; set; }
        public System.DateTime momento_ejecucion { get; set; }
        public string respuesta { get; set; }
    
        public virtual tarea tarea { get; set; }
    }
}
