//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public estados()
        {
            this.estado_dependencia = new HashSet<estado_dependencia>();
            this.estado_dependencia1 = new HashSet<estado_dependencia>();
            this.parametro_secuencia_estado = new HashSet<parametro_secuencia_estado>();
            this.proceso_workflow = new HashSet<proceso_workflow>();
            this.tareas_estado = new HashSet<tareas_estado>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_workflow { get; set; }
        public string nombre { get; set; }
        public Nullable<bool> estado_inicial { get; set; }
        public Nullable<bool> estado_final { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estado_dependencia> estado_dependencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estado_dependencia> estado_dependencia1 { get; set; }
        public virtual workflow workflow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parametro_secuencia_estado> parametro_secuencia_estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proceso_workflow> proceso_workflow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tareas_estado> tareas_estado { get; set; }
    }
}
