//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado_dependencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public estado_dependencia()
        {
            this.parametros_estado_dependencia = new HashSet<parametros_estado_dependencia>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_workflow { get; set; }
        public Nullable<int> id_estado_desde { get; set; }
        public Nullable<int> id_estado_hasta { get; set; }
        public Nullable<bool> parametrizable { get; set; }
    
        public virtual estados estados { get; set; }
        public virtual estados estados1 { get; set; }
        public virtual workflow workflow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parametros_estado_dependencia> parametros_estado_dependencia { get; set; }
    }
}
