//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametro_secuencia_estado
    {
        public int id { get; set; }
        public Nullable<int> id_parametro { get; set; }
        public int id_estado_siguiente { get; set; }
        public string valor_parametro { get; set; }
    
        public virtual estados estados { get; set; }
        public virtual parametros parametros { get; set; }
    }
}
