//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametros_estado_dependencia
    {
        public int id { get; set; }
        public Nullable<int> id_parametro { get; set; }
        public Nullable<int> id_estado_dependencia { get; set; }
    
        public virtual estado_dependencia estado_dependencia { get; set; }
        public virtual parametros parametros { get; set; }
    }
}
